# Generated by Django 4.1.4 on 2022-12-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interest_tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_required_skills",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user_skills", to="core.tag"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subtitle",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
