# Generated by Django 4.1.4 on 2022-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_company_alter_user_interest_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
