# Generated by Django 4.1.4 on 2022-12-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="image",
            field=models.ImageField(null=True, upload_to="companies"),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
        ),
    ]
