# Generated by Django 4.1.4 on 2022-12-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_company_image_alter_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequest",
            name="initiator",
            field=models.CharField(
                choices=[("student", "Student"), ("company", "Company")],
                default="student",
                max_length=15,
            ),
        ),
    ]
