# Generated by Django 4.1.4 on 2022-12-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_studentrequest_project_alter_studentrequest_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="desciption",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
