# Generated by Django 4.1.4 on 2022-12-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_studentprofile_desciption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="desciption",
            new_name="description",
        ),
    ]
