# Generated by Django 4.1.4 on 2022-12-11 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_desciption_studentprofile_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrowdFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CrowdFundingDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crowdfunding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.crowdfunding",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="crowdfunding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.crowdfunding",
            ),
        ),
    ]
