# Generated by Django 4.1.4 on 2022-12-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_crowdfunding_crowdfundingdonation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowdfunding",
            name="current",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
