# Generated by Django 4.1.4 on 2022-12-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_crowdfunding_current"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="crowdfunding",
        ),
        migrations.AddField(
            model_name="crowdfunding",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.project",
            ),
        ),
    ]
