# Generated by Django 4.1.4 on 2022-12-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_project_crowdfunding_crowdfunding_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfundingdonation",
            name="crowdfunding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.crowdfunding"
            ),
        ),
    ]
